### ISSUE TITLE
coffee-script is required before install

### ISSUE THREAD

**Issue by clemos** [oorabona/node-liblzma#6]
`coffee-script` is in the dependencies, but a the time of `ubs install`, it's not yet there.
So you have to install it manually beforehand.
Maybe it would be worth mentioning in the README and/or get rid of the dep, if possible (?).

**Comment by oorabona** [comment]
Hello @clemos ,

Indeed, I just did not have enough time to fix ```ubs``` so that it either does not depend on `coffee-script` at runtime (this is due to plugins examples) or to add `coffee-script` as a runtime dep.

I have almost fixed it, will publish a new version soon!

Thanks for your feedback!

**Comment by oorabona** [comment]
It should be fixed now with `ubs@0.6.6` and `node-libizma@1.0.3` !
