### ISSUE TITLE
Compressing high number of small payloads

### ISSUE THREAD

**Issue by behrad** [oorabona/node-liblzma#7]
I'm looking for the best approach to compress small message payloads to mobile clients in high concurrency.

1) Does LZMA give me any benefits for messages around 1k? Or I should send that sizes plain according to the processing overhead?

2) Is this module OK to perform around multiple thousand compressions per sec?

**Comment by joeyhub** [comment]
You should test it with a good sized and varied sample of the data you intend to send to find out. TIAS. Whether you get a significant gain is very much data dependent and at small sizes like that the window of opportunity tends to be much smaller.

Putting it simply: You can get a good gain on 1K or even less with LZMA but you're not likely to.

For messages that small some returns will be diminishing. For example it might fall lower than the minimum size for a lot of things (it would just be replaced with padding). Whatever you do at that size the gain is likely to be a moderate amount at best and might not pay off the cost in terms of CPU and memory. You're likely talking a few percentage points or less than a percent.

In some scenarios LZMA can prevail. It works particularly well with binary data. I haven't seen it do particularly amazingly for text of small sizes. In most cases overall it will be some small gains for zlib, some small gains for liblzma.

At 1K it can get close to twice the compression ratio with some data. If you're really luck your data might fall into that range and not be too variable. It's really constraining to rely on anything like that if it does happen to fit into that window of opportunity. If you send some data formatted differently down the pipe you'll likely lose the advantage. In more realistic scenarios where the data is more generally suited to LZMA you will probably be looking at a 5% to 15% improvement on average.

At that size you'll want to use raw encoding to get rid of the overhead.

Beyond that there's a few things that can be done, alternating between compression types, using a dictionary, further minimising the header (IE take away the dictionary size byte), etc. It's possible to perhaps try to format your data as well to make it more compressible but that's entirely dependent on the situation, it may not be possible at all. Ensuring that small packets are merge when possible (IE buffering until writable then compressing) can also yield good gains.
